### ISSUE TITLE
The rounded corners of the search input field are not being applied in editor.

### ISSUE THREAD

**Issue by torounit** [WordPress/twentytwentyfive#670] opened 2024-11-06 13:32 UTC
**Description**

The input[type=search] selector in wp-admin/css/forms.min.css overrides the CSS, resulting in a border-radius: 4px.

**Step-by-step reproduction instructions**

1. Go to Site Editor.
2. Add Search Block.

**Expected behavior**

border-radius: 3.125rem is applied.

**Screenshots**

### editor
![Image](https://github.com/user-attachments/assets/8c7c372f-77d9-43dd-9c33-cab83920b255)

### view
![Image](https://github.com/user-attachments/assets/34f3cf0d-a290-4f72-b2bc-eb266c25db6d)

**Environment info**

WordPress 6.7 RC3

**Additional context**

**Comment by carolinan** [comment] 2024-11-07 11:21
Hi
I believe this is the same issue that is reported here? https://github.com/WordPress/gutenberg/issues/66115

CSS specificity issues where the editor overrides either theme.json or user settings, needs to be opened in the Gutenberg GitHub repository, because they need to be fixed in the editor, not the themes.

**Comment by carolinan** [comment] 2024-11-11 06:32
I am not able to reproduce this unless I first change the theme style variation, so since I have not heard anything else, I am going to assume that this is a duplicate of the issue I linked in the last comment, and I will close this.

**Closed as completed by carolinan** 2024-11-11 06:32 UTC
Labels: [Type] Bug
