### ISSUE TITLE
Outline Button showing up differently on the editor and front end

### ISSUE THREAD

**Issue by beafialho** [WordPress/twentytwentyfive#560] opened 2024-10-11 11:14 UTC
I noticed the outline button's border is looking thicker in the editor than its correct border on front end.

|    Editor   | Front end |
| ----------- | ----------- |
|   ![Image](https://github.com/user-attachments/assets/c13c8266-833f-413c-93fc-f91dd4dd8504)   |   ![Image](https://github.com/user-attachments/assets/e5812a49-d5fd-440a-a1c9-c692eb46a3d2)   |

**Comment by juanfra** [comment] 2024-10-11 14:24
I can't reproduce this one.

https://github.com/user-attachments/assets/23175c42-7479-4de7-af12-3d638e0cc928

Are you using Gutenberg also?

**Comment by beafialho** [comment] 2024-10-11 14:46
> Are you using Gutenberg also?

Yes. I am on Safari, but I also see it on Firefox.

**Comment by juanfra** [comment] 2024-10-11 14:55
I am on Firefox. Still can't reproduce.

**Comment by beafialho** [comment] 2024-10-11 14:57
It's probably something having to do with my own setup maybe 🤔  I say we can close the issue if no one else can reproduce it.

**Comment by troychaplin** [comment] 2024-10-11 17:33
I just took a quick look in Firefox, Brave and Edge on Mac, all good

**Comment by giankocr** [comment] 2024-10-11 22:19
I try in Firefox, Brave and Edge on Mac, all good

Editor
![Image](https://github.com/user-attachments/assets/5ce0a7d2-cba3-4441-93c6-dce64b077e74)

FrontEnd
![Image](https://github.com/user-attachments/assets/7ef7ac81-ab6e-4dfc-9a98-7021751ac239)

**Comment by t-hamano** [comment] 2024-10-13 12:08
The outline button's style is defined [here](https://github.com/WordPress/twentytwentyfive/blob/385591043a55cfb769a8b81ddfe733d343ad7a8e/theme.json#L960-L974), and the outline width should be 1px in both the editor and the frontend:

![Image](https://github.com/user-attachments/assets/d8425a3c-da27-42e3-b098-c43ada70d838)

@beafialho In the screenshot you attached, it looks like the border width is bigger than 1px in the editor. Could you check the CSS in your browser developer tools to see why it's bigger?

**Comment by karmatosed** [comment] 2024-10-13 14:17
I also can't reproduce so for now my recommendation would be to close this, so as I am trying to help triage I will do that. We can always reopen though if anyone can reproduce.

**Closed as completed by karmatosed** 2024-10-13 14:17 UTC
Labels: [Type] Bug, [Priority] Low
