### ISSUE TITLE
After converting Group to Row images are not displayed anymore

### ISSUE THREAD

**Issue by oksanayoast** [WordPress/twentytwentyfive#586] opened 2024-10-17 12:48 UTC
**Description**

**Step-by-step reproduction instructions**
1. Inside the group add the grid with paragraphs and images
2. In block settings change "Group" to "Row" or to "Stack"
3. Check that images are not displayed anymore. See video

**Expected behavior**
Images Should be displayed

**Screenshots**
[Video](https://monosnap.com/file/0mkhtw8reMehZ5nPwFMaQEy9aNzfMo)

**Environment info**

**Additional context**

**Comment by juanfra** [comment] 2024-10-17 13:46
Thank you for reporting.

The issue is related to Gutenberg. Can you please open an issue in that repository? I'd encourage you to search if it was already reported. I'm going to close this issue for now.

**Closed as completed by juanfra** 2024-10-17 13:46 UTC
Labels: [Type] Bug
