### ISSUE TITLE
Unable to change background color when editing header

### ISSUE THREAD

**Issue by 369work** [WordPress/twentytwentyfive#642] opened 2024-10-28 07:50 UTC
**Description**
I tried to change the background color of the header by editing a template part in the theme editor.
I can change the text color, and although I can select the background color and gradient, the changes are not reflected.

**Step-by-step reproduction instructions**
1. Theme > Editor > pattern > header
2. Edit Selection
3. elect a style in the editor
4. Select background by color

**Expected behavior**
If you use other themes, the background color will change here.

**Screenshots**
![Image](https://github.com/user-attachments/assets/098f2cb7-4db6-461f-b827-42a40cda54ed)

**Environment info**
Windows11
Chrome
WordPress6.7RC1

**Additional context**
If it's expected that we can't choose, we don't want them to give us the option. It's confusing.

**Comment by carolinan** [comment] 2024-10-28 08:05
Hi, I am not able to reproduce this, can you add any more details?
The screenshot of the header does not match any existing header in the theme.

**Comment by juanfra** [comment] 2024-10-28 08:38
Thanks for reporting; I can't reproduce it.

https://github.com/user-attachments/assets/5408949e-001c-4bd0-bb12-ed636924fc9c

**Comment by 369work** [comment] 2024-10-28 15:53
Sorry. I reported this in the wrong place.
The topic was twentytwentyfour.
Sorry.

**Comment by juanfra** [comment] 2024-10-28 16:10
Thank you for the clarification. I'm closing this issue.

**Closed as completed by juanfra** 2024-10-28 16:10 UTC
Labels: [Type] Bug
