### ISSUE TITLE
More link in posts list has incorrect alignment.

### ISSUE THREAD

**Issue by joedolson** [WordPress/twentytwentyfive#491] opened 2024-10-03 01:28 UTC
**Description**

In the posts list, the '(more...)' link aligns to the left of the content area, rather than the left of the block area. This is because it's a direct descendant of `.is-layout-constrained` but is not a block level element. The `max-width` and `margin` attributes applied in `.is-layout-constrained > :where(:not(.alignleft):not(.alignright):not(.alignfull))` don't apply because the link is an inline element.

**Step-by-step reproduction instructions**

1. Activate the theme.
2. Set the front page to be a posts page.
3. Add a post that is long enough to trigger a more link.

**Expected behavior**

The link should align to the left edge of the post excerpt.

**Screenshots**

![Image](https://github.com/user-attachments/assets/b6e6fc79-c1e2-46b2-a90d-713014987717)

**Environment info**

Please share the browser(s) are you seeing the problem on.
Please share the Device you are using and operating system (e.g. "Desktop with Windows 10", "iPhone with iOS 14", etc.).
 - Device: Windows laptop
 - OS: Windows 11
 - Browser: Chrome 
 - Version: 129.0.6668.70 (Official Build) (64-bit)

**Comment by carolinan** [comment] 2024-10-03 02:25
Is the more link added by the user?

**Comment by carolinan** [comment] 2024-10-03 05:19
The only way I am able to reproduce this is if I create a post and add the more block to it.
The more block does not have a block class name, so as far as I know it can't be styled without custom CSS.

If I use the read more block instead, the link is contained within the content area. But this block just links to the top of the post; not to the bookmark where the content continues.

It is too much to expect that the user who is writing the content knows the difference between these two blocks, or knows that they can place the more block in a container like a group.

The question is if this must be be fixed in the theme or if it can wait until it is fixed in core / Gutenberg.
Because this does not only affect this theme.

**Comment by joedolson** [comment] 2024-10-03 20:51
This will apply to any text that is a direct ancestor of `.is-layout-constrained` and is not a block-level display element. I don't know how common that scenario is, practically speaking.

**Comment by carolinan** [comment] 2024-10-08 07:49
The only other block I know behaves this way is the HTML block. There may be others but I can't think of any right now.
If the constrained layout is removed from the post content block in the template, the wide and full width options will not be available. 

So another option is to add custom CSS targeting the `more-link` class on the more block's `<a>` tag.
- By default the theme shows the full post content on the archive pages, not the excerpt. So users may want to shorten the content using this block, and they will find the positioning unexpected.
- Not all users will know that they can wrap the block in a group or other container to change the position.
- If core improves the more block the custom CSS can be removed from that WordPress version and up.

**Closed as completed** 2024-10-08 09:30 UTC
Labels: [Type] Bug
