### ISSUE TITLE
Paragraph styles are broken in case we use "Annotation" style with different font styles

### ISSUE THREAD

**Issue by oksanayoast** [WordPress/twentytwentyfive#582] opened 2024-10-17 10:03 UTC
**Step-by-step reproduction instructions**
1. Create a post 
2. Add a paragraph with different font styles (bold, italic, etc)
![Image](https://github.com/user-attachments/assets/b609ef13-ff66-47e4-af08-e4650d2f40e0)

3. Switch to Block> Styles 
5. Choose "Annotation" style 
6. See that Paragraph Styling is broken

**Expected behavior**

Paragraph styles are behaving correctly.

**Screenshots**

![Image](https://github.com/user-attachments/assets/07d0a5dd-c848-4e26-a91d-45cd772dc6c7)

**Environment info**

**Additional context**

**Comment by juanfra** [comment] 2024-10-17 10:09
Thank you, Oksana!

This should have been resolved with [this PR](https://github.com/WordPress/twentytwentyfive/pull/581), which we merged recently (in the last hour). Can you please try to reproduce it with the latest trunk?

**Comment by carolinan** [comment] 2024-10-18 05:54
I am not able to reproduce this.

**Comment by carolinan** [comment] 2024-10-21 14:25
I am closing this as fixed, thank you.

**Closed as completed by carolinan** 2024-10-21 14:25 UTC
Labels: [Type] Bug
